### ISSUE TITLE
Add RiseClipse as an extra SCL validator

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-scl-validator#10]
As an engineer
I would like to check my configurations againt the RiseClipse OCL set
So I can be sure that my SCL configuration comply with with the RiseClipse

Background:
![image](https://user-images.githubusercontent.com/7427358/131860158-23196e65-08d4-4c0c-beee-aec436f335b8.png)
Source:
https://rise-clipse.pam-retd.fr/signin#about

The WG10 of the IEC decided to build standard OCL rules for IEC61850 validation.

**Comment by randy993** [comment]
- Validate on saving, maybe show the user what is valid and what not. Let the user decide wether to save or not
- Give the user the ability to validate the project and to see what is valid and what not
- Validate on predefined OCL rules (not customized by the user) ->

**Comment by dlabordus** [comment]
@Sander3003 Is this issue still needed? Or can we close it here and on Jira?
