### ISSUE TITLE
OCL selection

### ISSUE THREAD

**Issue by Sander3003** [com-pas/compas-scl-validator#15]
As an engineer
I want to select the default OCL rules per file type
So I can adjust them by default for my company

Background
The OCL rules are selected by software application.

**Comment by Sander3003** [comment]
The decision is made to upload OCL rules by de development team, this allows the codes to be tested.

**Comment by dlabordus** [comment]
It's probably easier to first use the RiseClipse GUI to create and test the OCL Rule/Files and when it's working let the development team deploy it with the SCL Validator to make it available for all engineers.

Remark: the OCL Files should work in all situations. Or if is specific for a SCL File Type put it in de correct "fileSpecifics" directory.
